steps:
  build:
    image: coralhl/woodpecker-buildx-plugin
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/hass-configurator-docker
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - latest
      - 0.5.2