steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/hass-configurator-docker
      tags:
      - latest
      - 0.5.2