steps:
  build:
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/hass-configurator-docker
      platform:  linux/amd64,linux/arm64
      tags:
      - latest
      - 0.5.2